---
# tasks file for roles/get-dn
- name: Get distinguished name
  aci_rest:
    host: "{{ inventory_hostname }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    validate_certs: no

    path: "/api/node/mo/uni/{{ mo }}.json?query-target=self"
    method: get
