---
# tasks file for roles/vlan-pool
- name: "{{ verb }} a VLAN pool"
  aci_vlan_pool:
    host: "{{ inventory_hostname }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    validate_certs: no

    pool: "{{ vlan_pool }}"
    pool_allocation_mode: static
    description: Josue VLANs
    state: "{{ playbook_action }}"
  delegate_to: localhost