---
# tasks file for roles/phys-dom
- name: "{{ verb }} physical domain"
  aci_rest:
    host: "{{ inventory_hostname }}"
    username: "{{ ansible_user }}"
    password: "{{ ansible_password }}"
    validate_certs: no

    path: "/api/node/mo/uni/phys-{{ domain }}.json"
    method: post
    content:
      physDomP:
        attributes:
          dn: "uni/phys-{{ domain }}"
          name: "{{ domain }}"
          rn: "phys-{{ domain }}"
          status: "{{ rest_action }}"
        children:
        - infraRsVlanNs:
            attributes:
              tDn: "uni/infra/vlanns-[{{ vlan_pool }}]-static"
              status: "{{ rest_action }}"
            children: []
